apiVersion: batch/v1
kind: Job
metadata:
  name: recreation-gov-scraper
  namespace: scrapers
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: recreation-gov-scraper
        image: ghcr.io/ai2160/recreation-gov-campsite-checker:latest
        env:
          - name: MG_KEY
            valueFrom:
              secretKeyRef:
                name: mg-secrets
                key: MG_KEY
          - name: MG_DOMAIN
            valueFrom:
              secretKeyRef:
                name: mg-secrets
                key: MG_DOMAIN
        command: ["python3"]
        args: ["camping.py --start-date {{ start_date }} --end-date {{ end_date }} {{ parks }}"]
      restartPolicy: Never
      imagePullSecrets:
        - name: gitpackage