# Workflow for recreation-gov-campsite-checker repo

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    # Build docker image
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to github repo
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ai2160
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and publish Docker Image to GitHub Packages Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_PASSWORD }}
